FROM amazoncorretto:11-alpine-jdk
MAINTAINER emaaristimuno
COPY target/NAME-YOUR-FILE-BUILD-SPRINGBOOT.jar NAME-YOUR-FILE-BUILDSPRINGBOOT.jar
ENTRYPOINT ["java","-jar","/NAME-YOUR-FILE-BUILD-SPRINGBOOT.jar"]